duckduckgo/privacy-reference-tests

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Initial tests for tracker radar domain matching rules.

initial TR domain tests

---

tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Update tds format

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/surrogates.js
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Initial surrogate tests for TR matching.  To verify, pull https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/800 and checkout this branch in the ref tests directory

surrogate tests

---

_scripts/linting.js
_scripts/schemas/tests.json
_template-new-feature/tests.json
tracker-radar-tests/TR-domain-matching/domain_matching_tests.json

`_template-new-feature` folder was not following expected naming convention and failed linitng. While fixing I also improved couple other nits. FYI @ladamski , but I don't think I should bother you with review.

Couple of small fixes.

---

_template-new-feature/README.md
global-privacy-control/README.md
global-privacy-control/config_reference.json
global-privacy-control/tests.json

Global Privacy Control tests as discussed in https://app.asana.com/0/0/1201277458549581/f
Draft integration with the extension in https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/947

GPC reference tests

---

referrer-trimming/README.md
referrer-trimming/config_reference.json
referrer-trimming/tests.json
referrer-trimming/tracker_radar_reference.json

Tech design discussion: https://app.asana.com/0/0/1201277458549585/f
There are three sections: header on navigational requests, header on subrequests and JS API. Tests are boringly similar between the three, but the context is different and some platforms will e.g. only support navigations but not subrequests due to platform limitations.

Referrer Trimming Tests

---

broken-site-reporting/README.md
broken-site-reporting/tests.json

Tech Design: https://app.asana.com/0/0/1201277458549584/f
Draft extension integration: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/972

Broken Site Reporting Tests

---

broken-site-reporting/tests.json

Added all path to native app specific tests

Add path to apps tests

---

storage-clearing/README.md
storage-clearing/tests.json

Tech Design: https://app.asana.com/0/0/1201277458549583/f

Fire button / fireproofing tests

---

block-third-party-tracking-cookies/README.md
block-third-party-tracking-cookies/config_reference.json
block-third-party-tracking-cookies/tests.json
block-third-party-tracking-cookies/tracker_radar_reference.json

Tech design: https://app.asana.com/0/0/1201277458549587/f

Tests for blocking tracking third party cookies

---

fingerprinting-protections/README.md
fingerprinting-protections/config_reference.json
fingerprinting-protections/init.js
fingerprinting-protections/tests.json

Tech Design: https://app.asana.com/0/0/1201277458549586/f

Tests for fingerprinting protections

---

fingerprinting-protections/README.md
tracker-radar-tests/TR-domain-matching/domain_matching_tests.json

Our extension is not doing the right thing, I wish it did :( … sooo I created this bug report: https://app.asana.com/0/892838074342800/1201806214352982/f

🐛 Disable ports test on extension

---

amp-protections/tests.json

This PR removes unneeded exceptions for an AMP test.

Update AMP tests exceptions

---

fingerprinting-protections/config_reference.json

To be in line with https://app.asana.com/0/72649045549333/1200810841420629/f

Add FP settings to test config

---

package.json

https://app.asana.com/0/1200606622205980/1202807740741711/f

Namespace package.json name

---

tracker-radar-tests/TR-domain-matching/README.md
tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/surrogates.txt

Task: https://app.asana.com/0/0/1203433047467081/f 
* Add new property to surrogate tests
* Change surrogates script to be testable by iOS/macOS

Change surrogate tests

---

global-privacy-control/README.md
global-privacy-control/tests.json

https://app.asana.com/0/1200606622205980/1203496117125023/f

Add tests for gpcHeaderEnabledSites

---

click-to-load/README.md
click-to-load/config_reference.json
click-to-load/tds_reference.json
click-to-load/tests.json

- Adjust the Facebook entity name and Click to Load feature name to
match the latest privacy-configuration.
- Add some more test entities and some more advanced test cases.

Improve Click to Load tests

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

https://app.asana.com/0/0/1204251230622271/f

Add more options tests

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json

https://app.asana.com/0/0/1204270522786108/f
There are two more tests failing on the test server that aren't failing for me locally, so I've added some more exceptions.

Add more Android options exceptions

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json

https://app.asana.com/0/1202552961248957/1204288515900643/f
Removing added exclusions for Android since we have merged option support now for Android.

Remove options exclusions for Android

---

tracker-radar-tests/TR-domain-matching/README.md
tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Asana Task URL: https://app.asana.com/0/0/1204381151340035/f
Also, there is a couple of surrogates tests moved to "surrogatesTests" dict, as previously these were not being evaluated properly on Apple platforms.

Disable not working tests on Apple platforms

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

https://app.asana.com/0/0/1204550083978882/f
Statuses:
- Android: https://github.com/duckduckgo/Android/actions/runs/4945879435 (all passing)
- iOS: Passing (manually ran the tests) (one exception, added & retested to verify all passing)
- Extension: passing (see CI tests for this PR)

Add tests for blocklist rule format

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

https://app.asana.com/0/0/1204504672745452/f
Extension passes all these tests. Might need some exceptions for Apple.
Status:
- Extensions: see PR CI
- Android: https://github.com/duckduckgo/Android/actions/runs/4978548575 (all passing)
- iOS: (failing multiple tests) (exceptions added) (all passing with exceptions)

Add tests for trailing algorithms

---

url-parameters/config_reference.json
url-parameters/tests.json

https://app.asana.com/0/0/1204622926998046/f

Update parameter tests to remove regex expectations

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Asana: https://app.asana.com/0/0/1204635006593396/f
Status:
- Extension (MV2) All passing - (see PR CI)
- Extension (MV3) - couple of failures, exceptions added
- Android: All passing - https://github.com/duckduckgo/Android/actions/runs/5032309031 (one unrelated failure, which is for URL parameters) / https://github.com/duckduckgo/Android/actions/runs/5038966107
- Apple: passing (manually verified. Exceptions added)

Add additional tracker blocking validation tests

---

url-parameters/tests.json

https://app.asana.com/0/488551667048375/1204621210866543/f
Enable URL parameter regex test on Android.

Enable URL parameter regex test

---

tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

Another case where BSK doesn't compile. https://app.asana.com/0/0/1204641354855486/f

Simplify regexp for Apple

---

storage-clearing/tests.json

Task/Issue URL: https://app.asana.com/0/0/1205202101916854/f
CC: @kdzwinel
Description:
Privacy reference tests adjusted according to the new Fire Button logic
Steps to test this PR:
1. Make sure tests are aligned with the new logic -> https://app.asana.com/0/0/1200195761608662/f
1. Make sure tests pass

Fire Button and Fireproofing tests adjusted based on new logic

---

broken-site-reporting/README.md
broken-site-reporting/multiple_report_tests.json

For: https://github.com/duckduckgo/duckduckgo-privacy-extension/pull/2306/files

Add support for multiple_report_tests for lastSentDay

---

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json

https://app.asana.com/0/0/1200195761608655/1205896398199238/f

Update surrogate reference tests to only allow scripts to be surrogates

---

broken-site-reporting/tests.json

https://app.asana.com/0/0/1207738418014187/f

Add country to locale

---

.github/workflows/test.yml

See also https://github.com/duckduckgo/BrowserServicesKit/pull/959

Switch PR Checks to macos-14 free runner

---

.github/workflows/test.yml

This PR updates the `test.yml` workflow to support the new Apple monorepo.

Update test workflow for Apple monorepo

---

.github/workflows/linting.yml
.github/workflows/release.yml
.github/workflows/test.yml

Per https://app.asana.com/0/0/1209404510169779/f

update ubuntu runners

---

.github/workflows/test.yml

**Task:** https://app.asana.com/0/inbox/1193060753408019/1209745503606409/1209750675560484/f
This PR updates BSK paths for some Apple file structure changes that are coming soon.
**How to test:**
This PR is pointing the test workflow at the upstream branch that implements the structure changes, so all you need to do here is check that CI is green. Once we verify that and the upstream changes are merged, I'll remove the test line and merge this PR.

Update BSK paths
