duckduckgo/privacy-reference-tests

tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
Domains need to be populated for some tests to pass.
=> populate domains hash

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
Initial swag at CNAME reference tests.  Interesting to note that the second test ("random allows sub.cname tracker") passes in the extension but returns "block" in iOS and fails.  
I've added it as an exemption for now (PR pending in iOS to support it), but I think its an interesting finding and worth discussing next week.
=> initial cname ref tests

CONTRIBUTING.md, README.md, _template-new-feature/README.md, _template-new-feature/config_reference.json, _template-new-feature/tests.json
As discussed in [Repo housekeeping](https://app.asana.com/0/0/1201321554045382/f):
- this specifies/documents the expected format for the folder structure and test files
- lists all options for `exceptPlatforms`
- provides a template for future tests
- plus some minor changes to the main readme
=> Rewrite contributing.md, add template for new tests

privacy-configuration/README.MD, privacy-configuration/config1_reference.json, privacy-configuration/config2_reference.json, privacy-configuration/config3_reference.json, privacy-configuration/test.json, privacy-configuration/tests.json
NOTE - might be worth merging https://github.com/duckduckgo/privacy-reference-tests/pull/10 first to make sure that this PR passes linting (I tested locally but you never know).
Implementation guidelines for the feature are here: https://app.asana.com/0/1198207348643509/1200553491728590/f
Test implementation in the web extension is waiting here: https://github.com/duckduckgo/duckduckgo-privacy-extension/compare/konrad/reference-tests-config
This follows the new format outlined here: https://app.asana.com/0/0/1201321554045382/f
=> Privacy configuration tests

privacy-configuration/README.MD, tracker-radar-tests/TR-domain-matching/README.md, tracker-radar-tests/TR-domain-matching/surrogates.js, tracker-radar-tests/TR-domain-matching/surrogates.txt
`surrogates.js` is in web-extension friendly format, but this format is hard to process for other platforms (it's a JS file). This PR adds `surrogates.txt` file which is closer to the real thing https://duckduckgo.com/contentblocking.js?l=surrogates . Additionally, I wrote up a small readme so that we provide some minimal integration instructions.
=> Provide surrogates file in a different format

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
Two tests:
- Known tracker can be CNAME'd to a domain that we don't block in which case we should still block it.
- Path from the original request should carry over to the uncloaked url and be checked against the `rules`
- plus a test for when cname entry maps to domain that doesn't have blocklist entry
Discussion: https://app.asana.com/0/0/1200328036456971/1201419292358852/f
=> Add an edge case where tracker is CNAME'd to a safe domain

_scripts/helpers/tracker-radar-checks.js, _scripts/linting.js, tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
@marcosholgado found an error in reference tracker radar blocklist that was causing one of the test to fail on Android. This PR fixes the issue and adds basic sanity checks for all `tracker_radar*` files (since those are usually crafted by hand for testing it's easy to make a mistake).
=> Tracker blocking test fix and Tracker Radar sanity checks

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
This PR adds an android exception for cname and types which are not yet supported by Android
=> Add android exceptions for types and cname

privacy-configuration/config1_reference.json, privacy-configuration/config2_reference.json, privacy-configuration/tests.json
https://app.asana.com/0/1125189844152671/1201514178819251
This PR adds eme as a new test only for Android and it excludes Android from the autofill tests (not yet implemented) and trackingCookies1p
=> Change tests for Android and add eme

tracker-radar-tests/TR-domain-matching/README.md, tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
#32 introduced port matching tests, but there are not yet supported on Apple platforms - disabling for now in order to embed tests repo in BSK library.
=> Disable port matching test in apple platforms

url-parameters/config_reference.json, url-parameters/tests.json
This change includes a number of improvements to the tracking
parameters protection reference tests:
- Expand the tests to cover more edge-cases such as case-sensitivity of
regular expression matching.
- Name the test cases consistently.
- Check allowlisted initiator domains and allowlisted subdomains are
handled correctly.
- Check that other edge-cases like parameter ordering and the
handling of duplicate parameters are handled correctly.
- Renamed example2.com to allowlisted.com to make the expected
behaviour of the tests more obvious.
=> Improve tracking parameters protection reference tests

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
Added two test cases that ensure that requests that match a Surrogate rule with matching exception are ignored in Trackers that have both the default ignore and block action.
=> Test Surrogate rules that match an exception

url-parameters/tests.json
This PR adds some tests that deal with URL encoded parameters. Whether we remove parameters or not, url encoded values should remain the same after the operation.
=> Add tests for url encoded parameters

https-upgrades/README.md, https-upgrades/https_dont_upgrade_hostnames.txt, https-upgrades/https_upgrade_hostnames.txt
For platforms not using the Bloom Filters for Smarter Encryption, it
is useful to also include the list of included/excluded domains
=> Add plain-text domains lists for the Smarter Encryption tests

url-parameters/tests.json
Since the expected params should not be modified, these two test cases should have an "&" separating the parameters in the `expectUrl`.
Tested on Apple + Android ✅
=> Add missing & to URL param tests

block-third-party-tracking-cookies/config_reference.json
This re-instates the changes from: https://github.com/duckduckgo/privacy-reference-tests/compare/c17944584aa6b78c72675af04facd003ba2f97e4...97c951aeb53f5f1a1a22fde4b5d6f53868d9b13e which were lost in https://github.com/duckduckgo/privacy-reference-tests/pull/47
The extension has been pointing at these files which was one issue; we could choose to delete them and the corresponding code from the extension.
The more important change is block-third-party-tracking-cookies/config_reference.json which enables the feature for the extension given it got renamed.
https://app.asana.com/0/0/1202815437790493/f
=> Cookie feature rename

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
Cloaked CNAME detection in Android is now supported: https://github.com/duckduckgo/Android/pull/2216.
=> Remove Android exception for CNAME test

tracker-radar-tests/TR-domain-matching/README.md, tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
Task: https://app.asana.com/0/0/1203158712142250/f
This PR re-enables the ports test on Android since we have now fixed the bug in https://github.com/duckduckgo/Android/pull/2402
=> Re-enable port test for Android

broken-site-reporting/tests.json
According to the [specs](https://app.asana.com/0/1198207348643509/1200202563872939)  the model version should be only sent for mobile browsers but the [Native app specific fields](https://github.com/duckduckgo/privacy-reference-tests/blob/331144c5e20629fadd4d067e15a318451a9d7b4a/broken-site-reporting/tests.json#L67) test also expect the model version for macOS and Windows.
This PR adds macOS and Windows to the exceptPlatforms for the test that expects a model.
=> Add desktop browsers to BSR specific test

global-privacy-control/config_reference.json
Task: https://app.asana.com/0/0/1203456821249393/f
This is necessary to comply to iOS/macOS GPC implementation
=> add gpcHeaderEnabledSites settings on GPC tests

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
This surfaces the issue found in https://app.asana.com/0/1200223097357040/1202312603683064/f where CNAME ignore is not handle the same on Android as other platforms.
=> Additional tracker blocking CNAME tests

storage-clearing/README.md
Storage cleaning tests are not influenced by the config file.
Details here: https://app.asana.com/0/0/1203552409531116/f
=> Remove wrong pseudo-code method call

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
With v4 of the block list, there can be rules with a custom rule
action (e.g. for the Click to Load feature). Platforms are expected to
ignore any such rules completely if the rule action isn't known to
them.
=> Add reference tests to ensure unsupported rule actions are ignored

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
https://app.asana.com/0/488551667048375/1203532296782616/f
This PR enables the CNAME same entity test on Android
=> Remove Android exception for CNAME same entity test

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
Asana task: https://app.asana.com/0/0/1203885070703634/f
This PR enables the "ignore image exception doesn't load tracker script" reference test on Android.
=> Enable type filtering reference test on Android

click-to-load/README.md, click-to-load/config_reference.json, click-to-load/surrogates_reference.txt, click-to-load/tds_reference.json, click-to-load/tests.json
Add reference tests for the Click to Load feature, to ensure that
platforms block/allow requests consistently.
Notes:
- These tests do not include the UI aspects of the feature, such as
what the placeholder elements look like.
- These changes are heavily based on Konrad's earlier work[1].
1 - https://github.com/duckduckgo/privacy-reference-tests/pull/30
=> Add Click to Load reference tests

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json
https://app.asana.com/0/0/1204192793460403/f
Option support is not yet implemented on Android, so I've added exceptions in the interim.
=> Add android exceptions for option tests

https-upgrades/README.md, https-upgrades/tests.json
cc: @RendijsSmukulis @kdzwinel 
1. exclude negative bloom filter tests as we're not using negative bloom filters
2. exclude ws:// tests, as webview2 does not support ws:// interception
Picking up where @RendijsSmukulis's [PR](https://github.com/duckduckgo/privacy-reference-tests/pull/46) and extending it, since I'll need to update to the latest reference tests for option blocking and unkown rule action handling.
=> Added exceptions for windows smarter encryption tests

.github/workflows/linting.yml, .github/workflows/test.yml
This makes it so we just have the one set of tests run when making a PR (not the extra, redundant branch-push tests), and keeps the branch tests for pushes to `main`.
Previously, whenever opening a PR/pushing to a PR, two copies of each test would be generated, which made the CI listing pretty noisy.
This also disables the tests if the only change is a documentation one (i.e., `*.md`) as is standard.
=> Reduce test noise when making PR

broken-site-reporting/README.md, broken-site-reporting/tests.json
iOS isn't sending privacy config version in reports currently. This adds exceptions to unblock the tests.
Also adds exceptions for the handling of etags until updated.
See https://app.asana.com/0/414709148257752/1204836191085934/f
- iOS passing (see https://app.asana.com/0/0/1204836191085934/1204857677987391/f)
- Android passing (see https://github.com/duckduckgo/Android/actions/runs/5321813596)
=> Add some temp iOS exceptions for site reporting

fingerprinting-protections/README.md, fingerprinting-protections/config_reference.json, fingerprinting-protections/init.js, fingerprinting-protections/tests.json
Reference tests for the protection implemented in https://github.com/duckduckgo/content-scope-scripts/pull/527
Note that the protection is not enabled on any platform yet, but I tested these with the extension locally.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204999444634510
=> Tests for the Harmful API protection

.github/workflows/test.yml
Run the MV2 and MV3 tests separately to make it easier to determine which is failing, and to allow MV3 to proceed regardless of MV2 failure.
=> Split MV2 and MV3 tests

block-third-party-tracking-cookies/config_reference.json
Not including these can break the cookie protection implementation in some cases.
=> Add cookie policies to 3p cookie config

broken-site-reporting/tests.json
Asana: https://app.asana.com/0/0/1204980841887189/f
Now that we have descriptions for broken site reports on Android, we should be checking the encoding works for them.
=> Remove exception on android for description encoding test

broken-site-reporting/README.md, broken-site-reporting/multiple_report_tests.json, broken-site-reporting/tests.json
Asana: https://app.asana.com/0/0/1205839123798774/f
Added tests for the new `protectionsState: 0 | 1' param in the breakage form
- Extension branch where this was tested: 
- https://github.com/duckduckgo/duckduckgo-privacy-extension/tree/shane/ref-tests
- Android, same
- https://github.com/duckduckgo/Android/pull/3821
- Passing test run https://github.com/duckduckgo/Android/actions/runs/6785317611
=> adding reference tests for protectionsState

amp-protections/config_reference.json
This key is needed to fix tests in https://github.com/duckduckgo/BrowserServicesKit/pull/611
=> Add deep extraction key to test config for AMP

.github/workflows/test.yml, fingerprinting-protections/README.md, fingerprinting-protections/init.js
**Asana task**: https://app.asana.com/0/0/1205123050397752/f
**Description**:
* Fix bug in temp storage override
* Small tweak to example pseudo-code
=> Fix fingerprinting test

tracker-radar-tests/TR-domain-matching/domain_matching_tests.json, tracker-radar-tests/TR-domain-matching/tracker_radar_reference.json
- Added a test that validates that, when Tracker is defined for a eTLD+2 domain (e.g. bad.etld-plus-two.site), tracker requests are correctly Ignored
- This validates a fix on windows, we recently discovered that `bad.third-party.site` had some sub-requests blocked due to 1st-vs-3rd party logic looking up eTLD+1 for tracker entity lookup (which is `third-party.site` - so in this case, did not find the `bad.third-party.site` Entity). This has now been fixed and is instead using the Tracker's Entity name to look up the Entity.
See https://app.asana.com/0/1199608453935138/1208394000709735/f for more detail.
=> Validate 'isFirstParty' logic for tracker that only has eTLD+2 domain defined

malicious-site-protection/canonicalization_tests.json
- Added exemptions for hosts that can't be parsed into URIs, as we'll never get into this state (webview2 will not provide invalid uris to the navigation handlers, it'll fail upstream)
=> Malicious Stie Ref Tests: Windows exemptions

suggestions/suggestions-regular-window-tabs.json
Changes `duck://newtab` -> `duck://ntp` on Windows as we've deprecated the legacy New Tab Page.
=> Migrate to new Windows NTP URL

malicious-site-protection/canonicalization_tests.json
Some of the canonicalization tests are broken for the windows-browser platform so we will skip them for now.
=> Temporarily skip broken canonicalization tests for windows-browser
